[MILESTONE 6] View
Maxwell011/Blog-App pull request #6
Opened 2023-02-02 09:08 UTC by Maxwell011

2023-02-02 10:04 UTC, elisha2kyakpo1 requested changes
Hi 👋 @Maxwell011, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description look good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 10:04 UTC, elisha2kyakpo1 commented on app/views/posts/index.html.erb
> +    <% end %>
- [ ] Kindly use the `last_five_comments` callback function to render the most recent comments for a post.

2023-02-02 10:04 UTC, elisha2kyakpo1 commented on app/views/users/show.html.erb
> +  </div>
- [ ] This button should take users to the post index page and not the home page.

2023-02-02 10:04 UTC, elisha2kyakpo1 commented on app/controllers/posts_controller.rb
> +  end
- [ ] Kindly fix the show action for post(s) post. I have posts I created on the Rails console, when I try to fetch a specific post using `http://localhost:3000/users/1/posts/1` I got an error.

![image](https://user-images.githubusercontent.com/53124548/216293419-809349c5-b2b3-4a27-88b8-de9fdf1fb8a7.png)

2023-02-02 10:04 UTC, elisha2kyakpo1 commented on app/views/posts/index.html.erb
> +    <div id="user_posts">
- [ ] The range loop prevents the display of all the posts using the button `See all posts`.

![all-posts](https://user-images.githubusercontent.com/53124548/216294563-10a10829-4322-4bb6-9688-25ea0ed13bf2.png)

2023-02-03 09:40 UTC, Maxwell011 commented on app/views/posts/index.html.erb
> +    <% end %>
Done

2023-02-03 10:06 UTC, sumairq approved these changes
### Hi @Maxwell011 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 12:44 UTC, merged